# Site Settings
title: Exploradores | Difundiendo la Biodiversidad de Monte Escobedo
email: thexploradores@gmail.com
description: Un sitio dedicado al conocimiento de la biodiversidad del Municipio de Monte Escabedo, Zacatecas. 
baseurl: "/Exploradores" # the subpath of your site, e.g. /blog
url: "https://github.com/JoseLuisManzanaresRivera/Exploradores/edit/gh-pages/_config.yml" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Exploradores
user_description: Exploradores, Difundiendo la biodiversidad de Monte Escobedo.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: github_JoseLuisManzanaresRivera
facebook_username: facebook_username
twitter_username: twitter@JLManzanaresR
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
